apiVersion: apps/v1
kind: Deployment
metadata:
  name: field
  namespace: olympsis
  labels:
    app: field-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: field-dep
  template:
    metadata:
      labels:
        app: field-dep
    spec:
      containers:
      - name: user
        image: olympsis/field:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 7002
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0