apiVersion: v1
kind: Service
metadata:
  name: field-svc
  namespace: olympsis
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: field-dep
  ports:
  - name: tcp-port
    protocol: TCP
    port: 80
    targetPort: 7002